### ISSUE TITLE
Text alignment inconsistent

### ISSUE THREAD

**Issue by macintoshhelper** [FACN1/litter-app#3]
**Design Suggestions**

- Select and buttons have inconsistent text alignment. `/report/report.html`.

```css
.form-input {
  text-align-last: center;
}
```

- Submit button could be separate too and have a higher material design elevation.

👍 CSS 😎
